db:
  container_name: postgres_shopee
  hostname: postgres
  image: postgres
  ports:
    - "5432:5432"
  expose:
    - "5432"
  volumes:
    - dbdata1:/var/lib/postgresql
  environment:
    - "POSTGRES_DB=shopee_test"
    - "POSTGRES_PASSWORD=password"
    - "POSTGRES_USER=postgres"
    - "POSTGRES_HOST=localhost"
    - "POSTGRES_PORT=5432"