# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvp', '0002_load_currency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='currencyexchangeratehistory',
            unique_together=set([('date', 'currency_exchange')]),
        ),
    ]
